# Generated by Django 6.0.7 on 2026-07-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('Hydrant', 'Hydrant'), ('Pond', 'Pond'), ('River', 'River'), ('Water Tank', 'Water Tank')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('Operational', 'Operational'), ('Under Maintenance', 'Under Maintenance'), ('Unavailable', 'Unavailable')], default='Operational', max_length=20)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'water_sources',
            },
        ),
    ]
