# Generated by Django 6.0.6 on 2026-07-11 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, help_text='Null if anonymous 1-click report; filled if logged-in citizen reports', null=True)),
                ('reporter_phone', models.CharField(blank=True, help_text='Captured manual phone input if available', max_length=20, null=True)),
                ('latitude', models.FloatField(help_text='Captured via HTML5 Geolocation API')),
                ('longitude', models.FloatField(help_text='Captured via HTML5 Geolocation API')),
                ('fire_scale', models.IntegerField(help_text='Severity Scale: 1, 2, or 3')),
                ('photo_url', models.URLField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Dispatched', 'Dispatched'), ('Under Control', 'Under Control'), ('Resolved', 'Resolved'), ('False Alarm', 'False Alarm')], default='Pending', help_text='Current status of the fire incident response', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the report was created')),
            ],
        ),
        migrations.CreateModel(
            name='FireStation',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('latitude', models.FloatField(help_text='For Leaflet/Google Maps routing')),
                ('longitude', models.FloatField(help_text='For Leaflet/Google Maps routing')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Maintenance', 'Maintenance')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fire_stations',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('Hydrant', 'Hydrant'), ('Pond', 'Pond'), ('River', 'River'), ('Water Tank', 'Water Tank')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('Operational', 'Operational'), ('Under Maintenance', 'Under Maintenance'), ('Unavailable', 'Unavailable')], default='Operational', max_length=20)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'water_sources',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataAccess.role')),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resources_deployed', models.TextField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataAccess.firereport')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataAccess.firestation')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataAccess.user')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataAccess.watersource')),
            ],
        ),
    ]
