# Generated by Django 6.0.6 on 2026-07-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataAccess', '0002_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='source',
        ),
        migrations.DeleteModel(
            name='WaterSource',
        ),
    ]
