# Generated by Django 6.0.7 on 2026-08-04 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAccess', '0003_remove_dispatch_source_delete_watersource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='DataAccess.firereport')),
            ],
            options={
                'db_table': 'tbl_notifications',
            },
        ),
    ]
