# Generated by Django 6.0.7 on 2026-08-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAccess', '0004_tbl_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='firereport',
            name='address',
            field=models.TextField(blank=True, help_text='Manual address input if GPS is disabled', null=True),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Captured via HTML5 Geolocation API', null=True),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Captured via HTML5 Geolocation API', null=True),
        ),
    ]
