# Generated by Django 6.0.7 on 2026-09-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAccess', '0005_firereport_address_alter_firereport_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firereport',
            name='fire_scale',
            field=models.IntegerField(choices=[(0, 'နယ်မြေခံ'), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], help_text='Severity Scale: 0=နယ်မြေခံ, 1=Level 1, 2=Level 2, 3=Level 3, 4=Level 4, 5=Level 5'),
        ),
    ]
