# Generated by Django 6.1.1 on 2026-10-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAccess', '0011_station_source_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='status',
            field=models.CharField(default='Dispatched', max_length=30),
        ),
    ]
