# Generated by Django 6.1.1 on 2026-10-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAccess', '0012_dispatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='firereport',
            name='source_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='firereport',
            name='source_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='fire_scale',
            field=models.IntegerField(choices=[(0, 'နယ်မြေခံ'), (1, 'အဆင့် ၁'), (2, 'အဆင့် ၂'), (3, 'အဆင့် ၃'), (4, 'အဆင့် ၄'), (5, 'အဆင့် ၅')], help_text='Severity Scale: 0=နယ်မြေခံ, 1=Level 1, 2=Level 2, 3=Level 3, 4=Level 4, 5=Level 5', null=True),
        ),
    ]
