# Generated by Django 6.0.6 on 2026-07-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, help_text='Null if anonymous 1-click report; filled if logged-in citizen reports', null=True)),
                ('reporter_phone', models.CharField(blank=True, help_text='Captured manual phone input if available', max_length=20, null=True)),
                ('latitude', models.FloatField(help_text='Captured via HTML5 Geolocation API')),
                ('longitude', models.FloatField(help_text='Captured via HTML5 Geolocation API')),
                ('fire_scale', models.IntegerField(help_text='Severity Scale: 1, 2, or 3')),
                ('photo_url', models.URLField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Dispatched', 'Dispatched'), ('Under Control', 'Under Control'), ('Resolved', 'Resolved'), ('False Alarm', 'False Alarm')], default='Pending', help_text='Current status of the fire incident response', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the report was created')),
            ],
        ),
    ]
